"""Add two column to ChatLog

Revision ID: 2db2f0d27451
Revises: 3ac8956aec99
Create Date: 2024-09-14 00:09:38.568171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db2f0d27451'
down_revision = '3ac8956aec99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serious_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('system_message', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.drop_column('system_message')
        batch_op.drop_column('serious_score')

    # ### end Alembic commands ###
