"""change serious_score to chatlog

Revision ID: 38ecb5d34dc1
Revises: 2db2f0d27451
Create Date: 2024-09-14 00:40:27.858469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ecb5d34dc1'
down_revision = '2db2f0d27451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.alter_column('serious_score',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_log', schema=None) as batch_op:
        batch_op.alter_column('serious_score',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
