"""Add ai_response column to ChatLog

Revision ID: 5cd9c20b4bde
Revises: 
Create Date: 2024-09-02 17:38:08.300418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd9c20b4bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(length=500), nullable=False),
    sa.Column('ai_response', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_chat_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_chat_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ai_response', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_log')
    # ### end Alembic commands ###
