"""Add link column to Tip model

Revision ID: 9a04bd404f02
Revises: 
Create Date: 2024-09-06 03:49:22.596940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a04bd404f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
